// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char DEVICE_LOGIN_NAME[]  = "f1661f9c-5faf-4237-a314-01c05fc54dd4"; // Device ID

const char SSID[]              = SECRET_SSID;    // Network SSID (name) 
const char PASS[]              = SECRET_OPTIONAL_PASS; // Network password (use for WPA, or use as key for WEP) GoN@10768275C
const char DEVICE_KEY[] = SECRET_DEVICE_KEY;  // Secret device password

void onLEDCONTROLLChange();
void onCalendarChange();

CloudDimmedLight lED_CONTROLL;
int CDO;
CloudSchedule calendar;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lED_CONTROLL, READWRITE, ON_CHANGE, onLEDCONTROLLChange);
  ArduinoCloud.addProperty(CDO, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(calendar, READWRITE, ON_CHANGE, onCalendarChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);